---
- name: Test changing the F5 hostname
  hosts: localhost
  tasks:
    - name: change the host name of the f5
      bigip_hostname:
        server: "{{ f5 }}"
        user: "{{ user }}"
        password: "{{ password }}"
        hostname: "f5testing"
        validate_certs: False
      delegate_to: localhost
