---
- name: Create a test user
  hosts: localhost
  tasks:
    - name: Create a test user
      bigip_user:
          server: "{{ f5 }}"
          user: "{{ user }}"
          password: "{{ password }}"
          username_credential: "johnd"
          password_credential: "password"
          full_name: "John Doe"
          partition_access: "all:admin"
          update_password: "on_create"
          state: "present"
