---
# This playbook runs a ranorex test
- name: RunRanorexTest
  hosts: all 

  tasks:
  - name: CreateRanorexScheduledTask
    #win_command: c:\pstools\psexec.exe -s -accepteula -i 1 {{ testexe }} {{ testparam }}
    #win_command: schtasks.exe /Run /TN {{ testparam }}
    #win_psexec:
      #command: "{{ testexe }} {{ testparam }}"
      #interactive: yes
      #system: yes
      #executable: C:\PsTools\PsExec.exe
    win_scheduled_task:
      name: AnsibleRanorexTest
      runlevel: highest
      store_password: false
      executable: "{{ testexe }} {{ testparam }}"
      state: present
      frequency: once
      time: 12am
      user: 'atsna\ranorexrt'
  - name: RunRanorexCommand
    win_command: schtasks.exe /Run /TN AnsibleRanorexTest
  - name: DisableRanorexScheduledTask
    win_scheduled_task:
      name: AnsibleRanorexTest
      runlevel: highest
      store_password: false
      executable: "{{ testexe }} {{ testparam }}"
      state: present
      frequency: once
      time: 12am
      user: 'atsna\ranorexrt'
      enabled: false
