---
# This playbook runs a ranorex test
- name: RunRanorexTest
  hosts: all 

  tasks:
  - name: CreateRanorexScheduledTask
    win_scheduled_task:
      name: AnsibleRanorexTest
      runlevel: highest
      store_password: false
      executable: "{{ testexe }}"
      arguments: "{{ testparam }}"
      state: present
      frequency: once
      time: 12am
      user: "{{ user }}"
      enabled: true
  - name: UpdateScheduledTask
    win_shell: $principal = New-ScheduledTaskPrincipal -UserID {{ user }} -RunLevel Highest; Set-ScheduledTask -TaskName AnsibleRanorexTest -Principal $principal
  - name: RunRanorexCommand
    win_shell: Start-ScheduledTask -TaskName AnsibleRanorexTest
  - pause:
      seconds: 30
  - name: DisableRanorexScheduledTask
    win_scheduled_task:
      name: AnsibleRanorexTest
      runlevel: highest
      store_password: false
      executable: "{{ testexe }}"
      arguments: "{{ testparam }}"
      state: present
      frequency: once
      time: 12am
      user: "{{ user }}"
      enabled: false
