---
# This playbook runs a ranorex test
- name: RunRanorexTest
  hosts: all 

  tasks:
  - name: CreateRanorexScheduledTask
    #win_command: c:\pstools\psexec.exe -s -accepteula -i 1 {{ testexe }} {{ testparam }}
    #win_command: schtasks.exe /Run /TN {{ testparam }}
    #win_psexec:
      #command: "{{ testexe }} {{ testparam }}"
      #interactive: yes
      #system: yes
      #executable: C:\PsTools\PsExec.exe
    win_scheduled_task:
      name: AnsibleRanorexTest
      runlevel: highest
      store_password: false
      executable: "{{ testexe }}"
      arguments: "{{ testparam }}"
      state: present
      frequency: once
      time: 12am
      user: 'ranorexrt@atsna.atsauto.net'
      enabled: true
  - name: UpdateScheduledTask
    win_shell: $principal = New-ScheduledTaskPrincipal -UserID ranorexrt@atsna.atsauto.net -RunLevel Highest; Set-ScheduledTask -TaskName AnsibleRanorexTest -Principal $principal
  - name: RunRanorexCommand
    #win_command: schtasks.exe /Run /TN AnsibleRanorexTest
    win_shell: Start-ScheduledTask -TaskName AnsibleRanorexTest
  - pause:
      seconds: 30
  - name: DisableRanorexScheduledTask
    win_scheduled_task:
      name: AnsibleRanorexTest
      runlevel: highest
      store_password: false
      executable: "{{ testexe }}"
      arguments: "{{ testparam }}"
      state: present
      frequency: once
      time: 12am
      user: 'ranorexrt@atsna.atsauto.net'
      enabled: false
