---
# This playbook runs a ranorex test
- name: RunRanorexTest
  hosts: all 

  tasks:
  - name: RunRanorexCommand
    win_command: c:\pstools\psexec.exe -accepteula -i {{ testexe }} {{ testparam }}
    #win_command: schtasks.exe /Run /TN {{ testparam }}
