---
- name: Shutdown VMs using PowerCLI
  hosts: "{{ inventory_hostname }}"
  tasks:
    - name: Run the PowerCLI script to start the shutdown
      win_shell: C:\temp\VMWareShutdown.ps1 {{ ordered_hosts }} {{ vcenter }}
